name: Deploy Backend to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Define image name
        id: vars
        run: echo "IMAGE=${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.AR_REPO_BACK || vars.AR_REPO }}/backend:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build & push with Cloud Build
        working-directory: backend
        run: gcloud builds submit --tag ${{ steps.vars.outputs.IMAGE }} --timeout=1200 .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.BACKEND_SERVICE_NAME || 'backend' }} \
            --image ${{ steps.vars.outputs.IMAGE }} \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --cpu ${{ vars.BACK_CPU || '1' }} \
            --memory ${{ vars.BACK_MEMORY || '512Mi' }} \
            --timeout ${{ vars.BACK_TIMEOUT || '60' }} \
            --concurrency ${{ vars.BACK_CONCURRENCY || '80' }} \
            --max-instances ${{ vars.BACK_MAX_INSTANCES || '3' }} \
            --min-instances ${{ vars.BACK_MIN_INSTANCES || '0' }} \
            --labels app=backend,env=${{ vars.ENV || 'prod' }} \
            ${{ vars.BACK_SERVICE_ACCOUNT && format('--service-account {0}', vars.BACK_SERVICE_ACCOUNT) || '' }} \
            --set-env-vars CORS_ORIGINS=${{ vars.CORS_ORIGINS || 'https://tu-frontend.a.run.app' }},UVICORN_WORKERS=${{ vars.UVICORN_WORKERS || '1' }},PYTHONUNBUFFERED=1

      - name: Show service URL
        run: gcloud run services describe ${{ vars.BACKEND_SERVICE_NAME || 'backend' }} --region ${{ vars.GCP_REGION }} --format='value(status.url)'
