name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Define image name
        id: vars
        run: echo "IMAGE=${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.AR_REPO }}/${{ vars.SERVICE_NAME }}:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build & push with Cloud Build
        run: gcloud builds submit --tag ${{ steps.vars.outputs.IMAGE }} --timeout=1200

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
            --image ${{ steps.vars.outputs.IMAGE }} \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --concurrency ${{ vars.CONCURRENCY || 80 }} \
            --max-instances ${{ vars.MAX_INSTANCES || 1 }} \
            --min-instances ${{ vars.MIN_INSTANCES || 0 }}

      - name: Show service URL
        run: gcloud run services describe ${{ vars.SERVICE_NAME }} --region ${{ vars.GCP_REGION }} --format='value(status.url)'
